#!/bin/bash

DATE=$( date '+%Y-%m-%d_%H%M%S' )
./obs-begin-sequence

if [[ $? -gt 0 ]] ; then
	echo "Error: obs-begin-sequence aborted. Is obs running?"
	exit 1
fi

# Run installation
./install-archlinux-inside-vm | tee ../archlinux-setup-vb_videos/$DATE.txt

./obs-end-sequence

# Save pastebin data to a local file
# Search for the "Pastebin urls" header, print to end of file, 
# grep only the sprunge.us urls, run echo and curl commands for each line
sed -n '/Pastebin urls/,$ p' ../archlinux-setup-vb_videos/$DATE.txt | grep "http://sprunge\.us/" | xargs -n1 -I % sh -c 'echo --- % ---; curl -q -- %' >> ../archlinux-setup-vb_videos/${DATE}_pastebins.txt

