#!/bin/bash

tmux new-session -d
tmux split-window -v

VBoxManage startvm "{d0f3631f-9f95-4907-a950-77c674bfcd84}" --type gui
# Press the home key so a) the first element is selected and b) auto-boot is prevented
# Doing this a couple of times since we don't know how long it takes
for i in `seq 1 7` ; do
    sleep 1
    VBoxManage controlvm "{d0f3631f-9f95-4907-a950-77c674bfcd84}" keyboardputscancode e0 47 e0 97
done

tmux send-keys -t 0:0.0 'watch --no-title --interval 0.5  curl -qs http://localhost:8080/vmstatus/CURRENTVM/get-stage/ ; exit' Enter

tmux new-window -d
tmux send-keys -t 0:1 'DISPLAY=:0.0 obs --disable-shutdown-check ; exit' Enter
sleep 5

tmux send-keys -t 0:0.1 'cd ~/archlinux-setup-vb' Enter
tmux send-keys -t 0:0.1 './run-installation ; sleep 4 && killall watch && killall obs ; exit' Enter
tmux a
